name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  TAG: ${{ github.ref_name }}

  # WINDOWS only
  SDL2_VERSION: 2.24.1
  SDL2_IMAGE_VERSION: 2.6.2
  SDL2_MIXER_VERSION: 2.6.2
  SDL2_TTF_VERSION: 2.20.1

  WINBUILDTYPE: Release

jobs:
  publish-linux:
    name: Publish Linux
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev
        sudo add-apt-repository universe
        sudo apt install libfuse2
    
    - name: Configure CMake
      run: cmake . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: make -j

    - name: Pack deb and rpm
      run: cpack -G "DEB;RPM"
      
    - name: Upload DEB
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: minesector.deb
        asset_name: minesector-linux64.deb
        overwrite: true
        tag: ${{ env.TAG }}
      
    - name: Upload RPM
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: minesector.rpm
        asset_name: minesector-linux64.rpm
        overwrite: true
        tag: ${{ env.TAG }}

    - name: Get LinuxDeploy
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage

    - name: Bundle resources for AppImage
      run: |
        ./configure -DCMAKE_INSTALL_PREFIX=/usr
        make install DESTDIR=AppDir

    - name: Build AppImage with LinuxDeploy
      run: |
        export VERSION=${{ env.TAG }}
        ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage --icon-file AppDir/usr/share/icons/hicolor/128x128/apps/minesector.png --desktop-file AppDir/usr/share/applications/minesector.desktop

    - name: Upload AppImage
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: MineSector-${{ env.TAG }}-x86_64.AppImage
        asset_name: MineSector-x86_64.AppImage
        overwrite: true
        tag: ${{ env.TAG }}

  publish-macos:
    name: Publish MacOS
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: brew install sdl2 sdl2_image sdl2_ttf sdl2_mixer
    
    - name: Configure CMake
      run: cmake . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: make -j

    - name: Pack Drag & Drop
      run: cpack -G "DragNDrop"
      
    - name: Upload package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: minesector.dmg
        asset_name: minesector-macos-x86_64.dmg
        overwrite: true
        tag: ${{ env.TAG }} 

  publish-win64:
    name: Publish Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: choco install ninja wget unzip

    - name: Install SDL2 mingw libs
      run: |
        $env:SDL2_FILE       = "SDL2-devel-${{ env.SDL2_VERSION }}-mingw.zip"
        $env:SDL2_IMAGE_FILE = "SDL2_image-devel-${{ env.SDL2_IMAGE_VERSION }}-mingw.zip"
        $env:SDL2_MIXER_FILE = "SDL2_mixer-devel-${{ env.SDL2_MIXER_VERSION }}-mingw.zip"
        $env:SDL2_TTF_FILE   = "SDL2_ttf-devel-${{ env.SDL2_TTF_VERSION }}-mingw.zip"

        wget.exe "https://github.com/libsdl-org/SDL/releases/download/release-${{env.SDL2_VERSION}}/${env:SDL2_FILE}"
        wget.exe "https://github.com/libsdl-org/SDL_image/releases/download/release-${{ env.SDL2_IMAGE_VERSION }}/${env:SDL2_IMAGE_FILE}"
        wget.exe "https://github.com/libsdl-org/SDL_ttf/releases/download/release-${{ env.SDL2_TTF_VERSION }}/${env:SDL2_TTF_FILE}"
        wget.exe "https://github.com/libsdl-org/SDL_mixer/releases/download/release-${{ env.SDL2_MIXER_VERSION }}/${env:SDL2_MIXER_FILE}"
        unzip.exe $env:SDL2_FILE
        unzip.exe $env:SDL2_IMAGE_FILE
        unzip.exe $env:SDL2_TTF_FILE
        unzip.exe $env:SDL2_MIXER_FILE
        rm *.zip

    - name: Configure
      run: |
        cmake . -DCMAKE_BUILD_TYPE=${{env.WINBUILDTYPE}} -G Ninja -DCMAKE_C_COMPILER="x86_64-w64-mingw32-gcc.exe" -DCMAKE_CXX_COMPILER="x86_64-w64-mingw32-g++.exe" -DCMAKE_PREFIX_PATH="./SDL2-${{env.SDL2_VERSION}}/cmake/;./SDL2_image-${{env.SDL2_IMAGE_VERSION}}/cmake/;./SDL2_mixer-${{env.SDL2_MIXER_VERSION}}/cmake/;./SDL2_ttf-${{env.SDL2_TTF_VERSION}}/cmake/;"

    - name: Build
      run: ninja

    - name: CPack msi installer
      run: cpack

    - name: Upload package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: minesector.msi
        asset_name: minesector-win64.msi
        overwrite: true
        tag: ${{ env.TAG }} 
